version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/citronix
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0074
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0074
      POSTGRES_DB: citronix
