version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-postgresql-nyc3-03556-do-user-18409800-0.g.db.ondigitalocean.com:25060/defaultdb?sslmode=require
      SPRING_DATASOURCE_USERNAME: doadmin
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: doadmin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: defaultdb
